config/routes.rb
Schedulator::Application.routes.draw do
  resources :teams

  resources :seasons do
    get :teams, on: :member
  end

  root :to => 'seasons#index'

end

app/models/division.rb
class Division < ActiveRecord::Base
  attr_accessible :name, :sport_id
  belongs_to :sport
  has_many :teams
end

app/models/season.rb
class Season < ActiveRecord::Base
  attr_accessible :name

  has_many :sports

  validates :name, presence: true

  def current_season_list
  	current_year = Time.now.year

  	seasons = [ "Winter #{current_year}",
  							"Spring #{current_year}",
  							"Summer #{current_year}",
  							"Fall #{current_year}"
  	 					]
  end
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  attr_accessible :active, :name
  has_one :season
  has_many :divisions
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :is_paid, :name, :player_count
  belongs_to :division
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seasons }
    end
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
    @season = Season.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/new
  # GET /seasons/new.json
  def new
    @season = Season.new
    @seasons = @season.current_season_list

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/1/edit
  def edit
    @season = Season.find(params[:id])
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(params[:season])
    @seasons = @season.current_season_list

    respond_to do |format|
      if @season.save
        format.html { redirect_to teams_url, notice: 'Season was successfully created. Please Add Teams.' }
        format.json { render json: @season, status: :created, location: @season }
      else
        format.html { render action: "new" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seasons/1
  # PUT /seasons/1.json
  def update
    @season = Season.find(params[:id])

    respond_to do |format|
      if @season.update_attributes(params[:season])
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season = Season.find(params[:id])
    @season.destroy

    respond_to do |format|
      format.html { redirect_to seasons_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = Team.find(params[:id])
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Schedulator"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/seasons/_form.html.haml
= simple_form_for(@season, html: { class: 'form-horizontal' } ) do |f|
	= f.error_notification
	
	.form-inputs
		.control-group
			= f.label :name, 'Season', { class: 'control-label'}
			.controls
				= f.select :name, options_for_select(@seasons), prompt: "Please select a season"

		.control-group
			.controls
				= f.button :submit

app/views/seasons/edit.html.haml
%h1 Editing season

= render 'form'

= link_to 'Show', @season
\|
= link_to 'Back', seasons_path

app/views/seasons/index.html.haml
%h1 Listing seasons

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @seasons.each do |season|
    %tr
      %td= season.name
      %td= link_to 'Show', season
      %td= link_to 'Edit', edit_season_path(season)
      %td= link_to 'Destroy', season, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Season', new_season_path

app/views/seasons/new.html.haml
%h1 New season

= render 'form'

= link_to 'Back', seasons_path

app/views/seasons/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @season.name

= link_to 'Edit', edit_season_path(@season)
\|
= link_to 'Back', seasons_path